# Generated by Django 5.2.11 on 2026-03-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_at_time',
            field=models.FloatField(null=True),
        ),
    ]
