# Generated by Django 5.2.11 on 2026-03-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_cartitem_price_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_at_time',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
