# Generated by Django 5.2.11 on 2026-03-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_productimage_image_url_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='selling_price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
