# Generated by Django 5.2.11 on 2026-03-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_productimage_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, null=True),
        ),
    ]
